### PR TITLE
Added support for .gz file extension

### PR DESCRIPTION
**Pull request by hwhsu**
Add hdfs CompressionCodecFactory and CompressionCodec for the LogRecordReader.java

### CODE REVIEW

**Comment by cgivre** [comment]
Can you share a working sample file?

**Comment by hwhsu** [comment]
This is the [sample file with .gz](https://drive.google.com/open?id=1ap8C0mLdgSdpk11_MUlb6Fk9yRfi6v0B). It works on my laptop environment (drill 1.12, hadoop 2.7.3)
### My Configuration
```json
    "log": {
      "type": "log",
      "extensions": [
        "log",
        "gz"
      ],
      "fieldNames": [
        "field1"
      ],
      "dataTypes": null,
      "pattern": "(\\d{3})",
      "errorOnMismatch": false,
      "dateFormat": null,
      "timeFormat": null
    }
```
### Query
```sql
select * from dfs.root.`sample.log.gz` limit 10
```
### Output:
field1
123
456
789

**Comment by cgivre** [comment]
Can you share the regex as well?

**Comment by hwhsu** [comment]
I also share my select statement and query result

**Pull request merged**
